//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrative
    {
        public int id { get; set; }
        public string Admin { get; set; }
        public string Unit { get; set; }
        public string SchoolMail { get; set; }
        public string Password { get; set; }
    }
}
