//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int id { get; set; }
        public Nullable<int> Personel { get; set; }
        public Nullable<int> Student { get; set; }
        public Nullable<int> Faculty { get; set; }
        public Nullable<int> Graduated { get; set; }
        public Nullable<int> Admin { get; set; }
    }
}
